<?php
error_reporting(0);
$title_name = basename($_SERVER['PHP_SELF']);
switch ($title_name) {
    case "index.php";
        $title_name = "Custom Software and Mobile App Development Company | Dev Pickles";
        $description = "Planning to launch your startup or scaling with a business software? Hire HOI's top-of-the-line mobile app development and software services.";
        $url = "";
        $indexfollow = "index, follow";
        break;
    case "about-us.php";
        $title_name = "About Us | Software Development Company In USA | Dev Pickles";
        $description = "We deliver quality results to our clients through an extensive understanding of software development for various platforms and audience types. Get in touch!";
        $url = "about-us";
        $indexfollow = "index, follow";
        break;
    case "blockchain-development.php";
        $title_name = "Leading Blockchain Development Company | Dev Pickles";
        $description = "Are you in search of top-rated blockchain development services?  Dev Pickles provides blockchain software solutions including custom blockchain development.";
        $url = "blockchain-development";
        $indexfollow = "index, follow";
        break;
    case "branding.php";
        $title_name = "Top-rated Professional Branding Company | Dev Pickles";
        $description = "HOI’s Branding Services · Logo Design · Social Media · Web Design · Digital Marketing · Marketing Strategy · Brand Identity.";
        $url = "branding";
        $indexfollow = "index, follow";
        break;
    case "content-writing.php";
        $title_name = "Conversion-centered Content Writing Services Company I Dev Pickles";
        $description = "Our content writing services include SEO-optimized content creation, web pages, blog articles, product descriptions, visual content and social media posts.";
        $url = "content-writing";
        $indexfollow = "index, follow";
        break;
    case "digital-marketing-services.php";
        $title_name = "Leading Digital Marketing Services Company | Dev Pickles";
        $description = "Dev Pickles is a full-service digital marketing agency. We offer internet marketing services for all businesses across all digital channels. Get a free consultation today!";
        $url = "digital-marketing-services";
        $indexfollow = "index, follow";
        break;
    case "industry.php";
        $title_name = "Industries We Serve | Marketing Development for Business Sectors";
        $description = "Dev Picklesbrings digital product development & marketing solutions for businesses. We bring our client’s visions into digital reality with result-oriented strategies.";
        $url = "industry";
        $indexfollow = "index, follow";
        break;
    case "mobile-app-development.php";
        $title_name = "Top Mobile App Development Services In The USA | Dev Pickles";
        $description = "Want to hire a mobile app development company? Dev Pickles offers reliable mobile app development services that are quick and within budget.";
        $url = "mobile-app-development";
        $indexfollow = "index, follow";
        break;
    case "portfolio.php";
        $title_name = "Our Portfolio | Best Delivered Projects | Dev Pickles";
        $description = "We bring our client's visions to digital reality. Discover some of our best-delivered projects that brought our clients more cash and loyal customers.";
        $url = "portfolio";
        $indexfollow = "index, follow";
        break;
    case "pricing.php";
        $title_name = "Premium Services at Affordable Prices | Dev Pickles";
        $description = "We have designed our pricing points, considering the varying requirements of various businesses and niches. Choose From Our Economical Packages";
        $url = "pricing";
        $indexfollow = "index, follow";
        break;
    case "services.php";
        $title_name = "Leading Software Development Services | Dev Pickles";
        $description = "From customization to full-cycle development services, we deliver reliable and cost-effective software solutions. Discover how we can help you";
        $url = "services";
        $indexfollow = "index, follow";
        break;
    case "website-design-and-development.php";
        $title_name = "Website Design and Development Services | Dev Pickles";
        $description = "Dev Pickles specializes in website design and development services. Our website developers provide expert web development and web design services to our clients.";
        $url = "website-design-and-development";
        $indexfollow = "index, follow";
        break;
    case "website-designing-services.php";
        $title_name = "Professional Website Design Company | Dev Pickles";
        $description = "Dev Picklesis a leading website design agency with diverse experience in helping brands optimize user experience through robust web design. Maximize your Digital Revenue Now!";
        $url = "website-designing-services";
        $indexfollow = "index, follow";
        break;
    case "website-development-services.php";
        $title_name = "Professional Website Development Services | Dev Pickles";
        $description = "Dev Picklesis a leading website development agency offering superior-quality web development services. Skyrocket your revenue with a multi-featured & fully-functional website!";
        $url = "website-development-services";
        $indexfollow = "index, follow";
        break;
    case "ecommerce-website-services.php";
        $title_name = "Professional eCommerce Website Development Company";
        $description = "Dev Picklesis an eCommerce website development company empowering B2C and B2B brands to establish their digital storefronts and digitize their businesses. Book a call Now!";
        $url = "ecommerce-website-services";
        $indexfollow = "index, follow";
        break;
    case "reviews.php";
        $title_name = "Reviews | Our Work Speaks For Itself | Dev Pickles";
        $description = "We value our clients & their feedback. Nothing makes us happier than when the hard work of our team gets appreciated. Our clients trust our work & that’s all we value.";
        $url = "reviews";
        $indexfollow = "index, follow";
        break;
    case "terms-and-conditions.php";
        $title_name = "Terms & Conditions | Dev Pickles";
        $description = "These Terms and Conditions constitute a legally binding agreement made between you, whether personally or on behalf of you & Dev Pickles. Read more!";
        $url = "terms-and-conditions";
        $indexfollow = "index, follow";
        break;
    case "privacypolicy.php";
        $title_name = "Privacy Policy | Dev Pickles";
        $description = "Dev Pickles LLC. respects the privacy of our users. This Privacy Policy explains how we collect, use, disclose & safeguard your information when you visit our website";
        $url = "privacypolicy";
        $indexfollow = "index, follow";
        break;
    case "contact-us.php";
        $title_name = "Contact Us | Dev Pickles";
        $description = "Our tech experts are eager to assist you in meeting your targets. Get in touch by calling us at 949-267-7994 or by writing us at info@devpickles.com.";
        $url = "contact-us";
        $indexfollow = "index, follow";
        break;
    case "thank-you.php";
        $title_name = "Thank You";
        $description = "";
        $url = "thank-you";
        $gtag_thankyou = "<script>gtag('event', 'conversion', {'send_to': 'AW-755340284/ThCFCPj32NgYEPynlugC'});</script>";
        $indexfollow = "index, follow";
        break;
    case "combo-packages.php";
        $title_name = "Dev Pickles";
        $description = "";
        $url = "combo-packages";
        $indexfollow = "index, follow";
        break;
    case "package-details-custom-website-business.php";
        $title_name = "Premium Services at Affordable Prices | Dev Pickles";
        $description = "We have designed our pricing points, considering the varying requirements of various businesses and niches. Choose From Our Economical Packages";
        $url = "package-details-custom-website-business";
        $indexfollow = "index, follow";
        break;
    case "package-details-custom-website-diamond.php";
        $title_name = "Premium Services at Affordable Prices | Dev Pickles";
        $description = "We have designed our pricing points, considering the varying requirements of various businesses and niches. Choose From Our Economical Packages";
        $url = "package-details-custom-website-diamond";
        $indexfollow = "index, follow";
        break;
    case "package-details-custom-website-gold.php";
        $title_name = "Premium Services at Affordable Prices | Dev Pickles";
        $description = "We have designed our pricing points, considering the varying requirements of various businesses and niches. Choose From Our Economical Packages";
        $url = "package-details-custom-website-gold";
        $indexfollow = "index, follow";
        break;
    case "package-details-custom-website-platinum.php";
        $title_name = "Premium Services at Affordable Prices | Dev Pickles";
        $description = "We have designed our pricing points, considering the varying requirements of various businesses and niches. Choose From Our Economical Packages";
        $url = "package-details-custom-website-platinum";
        $indexfollow = "index, follow";
        break;
    case "package-details-custom-website-silver.php";
        $title_name = "Premium Services at Affordable Prices | Dev Pickles";
        $description = "We have designed our pricing points, considering the varying requirements of various businesses and niches. Choose From Our Economical Packages";
        $url = "package-details-custom-website-silver";
        $indexfollow = "index, follow";
        break;
    case "package-details-custom-website-startup.php";
        $title_name = "Premium Services at Affordable Prices | Dev Pickles";
        $description = "We have designed our pricing points, considering the varying requirements of various businesses and niches. Choose From Our Economical Packages";
        $url = "package-details-custom-website-startup";
        $indexfollow = "index, follow";
        break;
    case "package-details-ecommerce-website-business.php";
        $title_name = "Premium Services at Affordable Prices | Dev Pickles";
        $description = "We have designed our pricing points, considering the varying requirements of various businesses and niches. Choose From Our Economical Packages";
        $url = "package-details-ecommerce-website-business";
        $indexfollow = "index, follow";
        break;
    case "package-details-ecommerce-website-gold.php";
        $title_name = "Premium Services at Affordable Prices | Dev Pickles";
        $description = "We have designed our pricing points, considering the varying requirements of various businesses and niches. Choose From Our Economical Packages";
        $url = "package-details-ecommerce-website-gold";
        $indexfollow = "index, follow";
        break;
    case "package-details-ecommerce-website-platinum.php";
        $title_name = "Premium Services at Affordable Prices | Dev Pickles";
        $description = "We have designed our pricing points, considering the varying requirements of various businesses and niches. Choose From Our Economical Packages";
        $url = "package-details-ecommerce-website-platinum";
        $indexfollow = "index, follow";
        break;
    case "package-details-ecommerce-website-silver.php";
        $title_name = "Premium Services at Affordable Prices | Dev Pickles";
        $description = "We have designed our pricing points, considering the varying requirements of various businesses and niches. Choose From Our Economical Packages";
        $url = "package-details-ecommerce-website-silver";
        $indexfollow = "index, follow";
        break;
    case "package-details-ecommerce-website-startup.php";
        $title_name = "Premium Services at Affordable Prices | Dev Pickles";
        $description = "We have designed our pricing points, considering the varying requirements of various businesses and niches. Choose From Our Economical Packages";
        $url = "package-details-ecommerce-website-startup";
        $indexfollow = "index, follow";
        break;
    case "package-details-shopify-website-business.php";
        $title_name = "Premium Services at Affordable Prices | Dev Pickles";
        $description = "We have designed our pricing points, considering the varying requirements of various businesses and niches. Choose From Our Economical Packages";
        $url = "package-details-shopify-website-business";
        $indexfollow = "index, follow";
        break;
    case "package-details-shopify-website-silver.php";
        $title_name = "Premium Services at Affordable Prices | Dev Pickles";
        $description = "We have designed our pricing points, considering the varying requirements of various businesses and niches. Choose From Our Economical Packages";
        $url = "package-details-shopify-website-silver";
        $indexfollow = "index, follow";
        break;
    case "package-details-shopify-website-startup.php";
        $title_name = "Premium Services at Affordable Prices | Dev Pickles";
        $description = "We have designed our pricing points, considering the varying requirements of various businesses and niches. Choose From Our Economical Packages";
        $url = "package-details-shopify-website-startup";
        $indexfollow = "index, follow";
        break;
    case "package-details-wordpress-website-business.php";
        $title_name = "Premium Services at Affordable Prices | Dev Pickles";
        $description = "We have designed our pricing points, considering the varying requirements of various businesses and niches. Choose From Our Economical Packages";
        $url = "package-details-wordpress-website-business";
        $indexfollow = "index, follow";
        break;
    case "package-details-wordpress-website-diamond.php";
        $title_name = "Premium Services at Affordable Prices | Dev Pickles";
        $description = "We have designed our pricing points, considering the varying requirements of various businesses and niches. Choose From Our Economical Packages";
        $url = "package-details-wordpress-website-diamond";
        $indexfollow = "index, follow";
        break;
    case "package-details-wordpress-website-gold.php";
        $title_name = "Premium Services at Affordable Prices | Dev Pickles";
        $description = "We have designed our pricing points, considering the varying requirements of various businesses and niches. Choose From Our Economical Packages";
        $url = "package-details-wordpress-website-gold";
        $indexfollow = "index, follow";
        break;
    case "package-details-wordpress-website-platinum.php";
        $title_name = "Premium Services at Affordable Prices | Dev Pickles";
        $description = "We have designed our pricing points, considering the varying requirements of various businesses and niches. Choose From Our Economical Packages";
        $url = "package-details-wordpress-website-platinum";
        $indexfollow = "index, follow";
        break;
    case "package-details-wordpress-website-silver.php";
        $title_name = "Premium Services at Affordable Prices | Dev Pickles";
        $description = "We have designed our pricing points, considering the varying requirements of various businesses and niches. Choose From Our Economical Packages";
        $url = "package-details-wordpress-website-silver";
        $indexfollow = "index, follow";
        break;
    case "package-details-wordpress-website-startup.php";
        $title_name = "Premium Services at Affordable Prices | Dev Pickles";
        $description = "We have designed our pricing points, considering the varying requirements of various businesses and niches. Choose From Our Economical Packages";
        $url = "package-details-wordpress-website-startup";
        $indexfollow = "index, follow";
        break;

        // Priority3 Links

    case "custom-website-design-and-development.php";
        $title_name = "Custom Website Design and Development Services | Dev Pickles";
        $description = "We provide custom website design & custom web development services that deliver exceptional websites that engage, inspire, & drive results.";
        $url = "custom-website-design-and-development";
        $indexfollow = "index, follow";
        break;
    case "full-stack-development.php";
        $title_name = "Top-Rated Full Stack Development Services | Dev Pickles";
        $description = "Looking to hire a full stack developer? We are a leading full stack development company with experience in both front-end and back-end technologies.";
        $url = "full-stack-development";
        $indexfollow = "index, follow";
        break;
    case "shopify-website-development.php";
        $title_name = "Shopify Website Development Services | Dev Pickles";
        $description = "Get your Shopify store up and running with complete custom solutions. We provide full-cycle Shopify website design and development services for your projects.";
        $url = "shopify-website-development";
        $indexfollow = "index, follow";
        break;
    case "ecommerce-website-development.php";
        $title_name = "E-commerce Website Design & Development Company | Dev Pickles";
        $description = "At Dev Pickles, we provide expert eCommerce website design and development services that enhance the appeal of your website and turn visitors into buyers.";
        $url = "ecommerce-website-development";
        $indexfollow = "index, follow";
        break;
    case "wordpress-design-and-development.php";
        $title_name = "WordPress Website Design & Development Services | Dev Pickles";
        $description = "From stunning designs to seamless functionality, our WordPress website design and development services offer tailor-made solutions that drive results.";
        $url = "wordpress-design-and-development";
        $indexfollow = "index, follow";
        break;
    case "ios-app-development.php";
        $title_name = " Leading IOS App Development Company | Dev Pickles";
        $description = "Looking for a trustworthy iPhone app development company? Dev Pickles offers the best-in-class IOS app development services.";
        $url = "ios-app-development";
        $indexfollow = "index, follow";
        break;
    case "android-app-development.php";
        $title_name = "#1 Android App Development Services Company | Dev Pickles";
        $description = "Looking for top-quality and cost-effective Android app development services? Dev Pickles is here to fulfill all your app development needs.";
        $url = "android-app-development";
        $indexfollow = "index, follow";
        break;
    case "cross-platform-app-development.php";
        $title_name = "Top-Ranked Cross-Platform App Development Company | Dev Pickles";
        $description = "Planning to hire expert cross-platform app development services to build a multi-platform app? Dev Pickles can help!";
        $url = "cross-platform-app-development";
        $indexfollow = "index, follow";
        break;

        // Priority4 Links       

    case "web-application-development.php";
        $title_name = "Progressive Web Application Development Company | Dev Pickles";
        $description = "Want to create a corporate and customer-driven web application? We offer end-to-end web application development services for businesses in various industries.";
        $url = "web-application-development";
        $indexfollow = "index, follow";
        break;
    case "website-maintenance.php";
        $title_name = "Reliable Website Maintenance Services | Dev Pickles";
        $description = "Looking for trusted website maintenance and support services? We offer solutions to keep your website up-to-date, secure and performing at its best.";
        $url = "website-maintenance";
        $indexfollow = "index, follow";
        break;
    case "magento-development.php";
        $title_name = "Top-Rated Magento Website Development Company | Dev Pickles";
        $description = "Elevate your online business with top-notch Magento website development and design services. We create bespoke user-friendly e-commerce solutions.";
        $url = "magento-development";
        $indexfollow = "index, follow";
        break;
    case "react-native-development.php";
        $title_name = "Leading React Native App Development Company| Dev Pickles";
        $description = "Planning to accelerate your business processes with an app? Get HOI's React Native App Development Services for faster app development and quick turnaround.";
        $url = "react-native-development";
        $indexfollow = "index, follow";
        break;
    case "python-development.php";
        $title_name = "Python Development Services | Dev Pickles";
        $description = "Dev Picklesis a professional Python development company, offering high-quality Python development services to build complex web platforms and backend systems.";
        $url = "python-development";
        $indexfollow = "index, follow";
        break;
    case "crm-web-portal.php";
        $title_name = "CRM Web Portal Development Company | Dev Pickles";
        $description = "Looking to optimize interactions with a CRM web portal? We offer expert CRM web portal development services to elevate customer engagement effortlessly.";
        $url = "crm-web-portal";
        $indexfollow = "index, follow";
        break;
    case "b2b-and-b2c-web-portals.php";
        $title_name = "Leading B2B & B2C Web Portals Development Company | Dev Pickles";
        $description = "Dev Pickles offers Custom B2C-B2B web portal development services at an affordable price just according to your business requirement.";
        $url = "b2b-and-b2c-web-portals";
        $indexfollow = "index, follow";
        break;
    case "custom-software-development.php";
        $title_name = "Custom Software Development Company | Dev Pickles";
        $description = "Looking for custom software development services? Get custom software solutions for your business needs with our expert team.";
        $url = "custom-software-development";
        $indexfollow = "index, follow";
        break;
    case "saas-development.php";
        $title_name = "#1 SaaS Development Company | SaaS Development Services";
        $description = "Discover unparalleled SaaS development services tailored to your business needs. Our experts craft cutting-edge solutions to drive efficiency and growth.";
        $url = "saas-development";
        $indexfollow = "index, follow";
        break;

        // Priority5 Links  

    case "amazon-paid-marketing.php";
        $title_name = "Leading Amazon Marketing Agency | Dev Pickles";
        $description = "At Dev Pickles, a full-service Amazon agency, we take a holistic approach to creating your custom-designed Amazon marketing agency campaign";
        $url = "amazon-paid-marketing";
        $indexfollow = "index, follow";
        break;
    case "bing-paid-marketing.php";
        $title_name = "Bing Paid Marketing | Dev Pickles";
        $description = "";
        $url = "bing-paid-marketing";
        $indexfollow = "index, follow";
        break;
    case "nft-consulting-services.php";
        $title_name = "Top-Tier NFT Consulting Services | #1 NFT Consulting Company";
        $description = "Are you in need of a secure NFT channel? Dev Pickles is a leading NFT consulting company offering consultancy for both crypto and NFT projects.";
        $url = "nft-consulting-services";
        $indexfollow = "index, follow";
        break;
    case "nft-marketplace-development.php";
        $title_name = "Top-Rated NFT Marketplace Development Company | Dev Pickles";
        $description = "Looking for an NFT marketplace development company? Our cutting-edge NFT marketplace development services provide a seamless experience for buyers and sellers.";
        $url = "nft-marketplace-development";
        $indexfollow = "index, follow";
        break;
    case "search-engine-optimization.php";
        $title_name = "Top Rated SEO Services Agency | Dev Pickles";
        $description = "Dev Pickles is a search engine optimization company that provides comprehensive search engine marketing results.";
        $url = "search-engine-optimization";
        $indexfollow = "index, follow";
        break;
    case "social-media-marketing.php";
        $title_name = "Top Rated Social Media Marketing Services Agency | Dev Pickles";
        $description = "Share your brand story, connect with your target audience, and be identified as an industry leader through HOI's social media marketing services";
        $url = "social-media-marketing";
        $indexfollow = "index, follow";
        break;
    case "email-marketing-services.php";
        $title_name = "Top-rated Email Marketing Company | Dev Pickles";
        $description = "We are a full-service email marketing agency offering email campaign management, setting up automation, template production & much more.";
        $url = "email-marketing-services";
        $indexfollow = "index, follow";
        break;
    case "google-paid-marketing.php";
        $title_name = "Leading Google PPC Agency | Dev Pickles";
        $description = "Driving qualified traffic to your website with our PPC Services. We have significant experience in developing, setting up, and managing PPC campaigns for clients.";
        $url = "google-paid-marketing";
        $indexfollow = "index, follow";
        break;
    case "game-development.php";
        $title_name = "Leading Game Development Company in USA | Dev Pickles";
        $description = "Planning to launching a mobile game with stunning graphics and high-end user experience? Check HOI’s game development services and create immersive experiences for players.";
        $url = "game-development";
        $indexfollow = "index, follow";
        break;
    case "dapp-development.php";
        $title_name = "DApp Development Company | Dapp Development Services";
        $description = "We are a custom software and mobile app development company offering decentralized dApp development services harnessing the power of blockchain technology.";
        $url = "dapp-development";
        $indexfollow = "index, follow";
        break;
        case "faq.php";
            $title_name = "Frequently Asked Questions | Dev Pickles: Your Queries Answered";
            $description = "Explore our comprehensive FAQs page to find answers to common questions about Dev Pickles. From Services inquiries to troubleshooting, get the information you need conveniently in one place and more!";
            $url = "faq";
            $indexfollow = "index, follow";
            break;
    case "404.php";
        $title_name = "404 Not Found | Dev Pickles";
        $description = "";
        $url = "https://devpickles.com/404";
        $indexfollow = "noindex, nofollow";
        $indexfollow = "noindex, nofollow";
        break;
}

/**** PHONE NUMBER ****/

$phone_number = "(551) 290-8897";

?>